<template>
  <section class="mx-auto w-full max-w-5xl px-4 pb-16 pt-24 sm:px-6 lg:px-8"><div v-if="loading" class="space-y-3"><div class="h-5 w-16 animate-pulse rounded bg-[var(--landing-surface-strong)]" /><div class="h-8 w-72 animate-pulse rounded bg-[var(--landing-surface-strong)]" /></div><div v-else-if="errorMessage" class="rounded-lg border border-red-500/30 bg-red-500/10 p-6 text-sm text-red-200">{{ errorMessage }}<button type="button" class="ml-3 underline" @click="emit('retry')">{{ t('modelMarketplace.error.retry') }}</button></div><div v-else-if="!model" class="py-16 text-center"><h2 class="text-base font-semibold">{{ t('Model not found') }}</h2><RouterLink to="/pricing" class="mt-4 inline-flex rounded-md border border-[var(--landing-border)] px-3 py-2 text-sm">{{ t('Back to Models') }}</RouterLink></div><div v-else><RouterLink to="/pricing" class="mb-8 inline-flex items-center gap-2 rounded-md px-2 py-1.5 text-sm text-[var(--landing-fg-soft)] hover:bg-[var(--landing-surface)] hover:text-[var(--landing-fg)]">← {{ t('modelMarketplace.backToModels') }}</RouterLink><p class="text-sm text-[var(--landing-fg-soft)]">{{ platformName }}</p><h1 class="mt-1 break-all font-mono text-2xl font-semibold text-[var(--landing-fg)]">{{ model.name }}</h1><p class="mt-2 text-sm text-[var(--landing-fg-soft)]">{{ t('modelMarketplace.providerCount', { count: model.providers.length }) }}</p><div class="mt-8"><PricingDetailNav v-model="activeSection" /><div class="mt-8"><PricingModelDetails :model="model" :active-section="activeSection" /><PricingQuickStart v-if="activeSection === 'apps'" class="mt-8" :api-origin="apiOrigin" :model-name="model.name" /></div></div></div></section>
</template>
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import type { PublicPricingCatalogue } from '@/api/pricing'
import PricingDetailNav from './PricingDetailNav.vue'; import PricingModelDetails from './PricingModelDetails.vue'; import PricingQuickStart from './PricingQuickStart.vue'
const props = defineProps<{ marketplace: PublicPricingCatalogue | null; modelId: string; loading: boolean; errorMessage: string; apiOrigin: string }>(); const emit = defineEmits<{ retry: [] }>(); const { t } = useI18n(); const activeSection = ref<'providers' | 'pricing' | 'performance' | 'uptime' | 'benchmarks' | 'apps' | 'activity'>('providers')
const model = computed(() => props.marketplace?.platforms.flatMap((platform) => platform.models).find((item) => item.name === props.modelId))
const platformName = computed(() => props.marketplace?.platforms.find((platform) => platform.models.some((item) => item.name === props.modelId))?.name ?? '')
</script>
