services:
  sub2api:
    image: ${SUB2API_IMAGE:?SUB2API_IMAGE is required}
    container_name: quotajet-next
    volumes:
      - /www/data/sub2api/quotajet-next:/app/data:Z
    environment:
      - SERVER_TRUSTED_PROXIES=172.30.255.1/32
      - SECURITY_TRUST_FORWARDED_IP_FOR_API_KEY_ACL=false

  postgres:
    container_name: postgres.quotajet-next
    volumes:
      - /www/data/postgres/quotajet-next:/var/lib/postgresql/data:Z

  redis:
    container_name: redis.quotajet-next
    volumes:
      - /www/data/redis/quotajet-next:/data:Z

networks:
  sub2api-network:
    ipam:
      config:
        - subnet: 172.30.255.0/28
          gateway: 172.30.255.1
